#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Creates a new browser-use Python script template.

.DESCRIPTION
    Generates a ready-to-use browser-use Python script with common configurations.

.PARAMETER OutputPath
    Path where the script will be created (default: browser-use-agent.py)

.PARAMETER LlmProvider
    LLM provider to use: OpenAI, Anthropic, Google, DeepSeek, BrowserUse (default: BrowserUse)

.PARAMETER Model
    Specific model name (optional, uses provider defaults)

.PARAMETER UseCloud
    Include Browser Use Cloud configuration

.EXAMPLE
    .\New-BrowserUseScript.ps1 -OutputPath my-agent.py
    Creates a basic browser-use script.

.EXAMPLE
    .\New-BrowserUseScript.ps1 -OutputPath my-agent.py -LlmProvider OpenAI -Model "gpt-4o"
    Creates a script configured for OpenAI GPT-4o.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$OutputPath = 'browser-use-agent.py',

    [Parameter(Mandatory=$false)]
    [ValidateSet('OpenAI', 'Anthropic', 'Google', 'DeepSeek', 'BrowserUse', 'Grok', 'Novita', 'AzureOpenAI')]
    [string]$LlmProvider = 'BrowserUse',

    [Parameter(Mandatory=$false)]
    [string]$Model,

    [Parameter(Mandatory=$false)]
    [switch]$UseCloud
)

$InformationPreference = 'Continue'
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Build LLM initialization code
$llmCode = switch ($LlmProvider) {
    'OpenAI' {
        $modelName = if ($Model) { $Model } else { 'gpt-4o-mini' }
        "from browser_use.llm import ChatOpenAI`n    llm = ChatOpenAI(model=`"$modelName`", temperature=1.0)"
    }
    'Anthropic' {
        $modelName = if ($Model) { $Model } else { 'claude-3-5-sonnet-20241022' }
        "from browser_use.llm import ChatAnthropic`n    llm = ChatAnthropic(model=`"$modelName`", temperature=1.0)"
    }
    'Google' {
        $modelName = if ($Model) { $Model } else { 'gemini-2.0-flash-exp' }
        "from browser_use.llm import ChatGoogle`n    llm = ChatGoogle(model=`"$modelName`", temperature=1.0)"
    }
    'DeepSeek' {
        $modelName = if ($Model) { $Model } else { 'deepseek-chat' }
        "from browser_use.llm import ChatDeepSeek`n    llm = ChatDeepSeek(model=`"$modelName`", temperature=1.0)"
    }
    'Grok' {
        $modelName = if ($Model) { $Model } else { 'grok-beta' }
        "from browser_use.llm import ChatGrok`n    llm = ChatGrok(model=`"$modelName`", temperature=1.0)"
    }
    'Novita' {
        $modelName = if ($Model) { $Model } else { 'novita-llama-3.1-70b' }
        "from browser_use.llm import ChatNovita`n    llm = ChatNovita(model=`"$modelName`", temperature=1.0)"
    }
    'AzureOpenAI' {
        $modelName = if ($Model) { $Model } else { 'gpt-4o' }
        "from browser_use.llm import ChatAzureOpenAI`n    llm = ChatAzureOpenAI(`n        endpoint=os.getenv(`"AZURE_OPENAI_ENDPOINT`"),`n        api_key=os.getenv(`"AZURE_OPENAI_KEY`"),`n        model=`"$modelName`",`n        temperature=1.0`n    )"
    }
    default {
        "from browser_use.llm import ChatBrowserUse`n    llm = ChatBrowserUse()"
    }
}

$browserConfig = if ($UseCloud) { "Browser(use_cloud=True)" } else { "Browser()" }

$scriptContent = @"
#!/usr/bin/env python3
"""
Browser-use agent script
Generated by New-BrowserUseScript.ps1
"""

import asyncio
import os
from dotenv import load_dotenv
from browser_use import Agent, Browser
$($llmCode -replace '    ', '')

async def main():
    # Load environment variables from .env file
    load_dotenv()

    # Initialize browser
    browser = $browserConfig

    # Initialize LLM
    $llmCode

    # Create agent
    agent = Agent(
        task="Your task description here",
        llm=llm,
        browser=browser,
    )

    # Run agent
    history = await agent.run()
    print("Task completed!")
    return history

if __name__ == "__main__":
    asyncio.run(main())
"@

try {
    $scriptContent | Out-File -FilePath $OutputPath -Encoding utf8
    Write-Information "`e[32m✓ Created browser-use script: $OutputPath`e[0m"
    Write-Information "`e[36mConfigured for LLM Provider: $LlmProvider`e[0m"
    if ($Model) {
        Write-Information "`e[36mModel: $Model`e[0m"
    }
    if ($UseCloud) {
        Write-Information "`e[36mBrowser Use Cloud: Enabled`e[0m"
    }
    Write-Information "`e[33mDon't forget to:`e[0m"
    Write-Information "`e[33m  1. Update the task description`e[0m"
    Write-Information "`e[33m  2. Set API keys in .env file`e[0m"
    Write-Information "`e[33m  3. Install dependencies: pip install browser-use python-dotenv`e[0m"

} catch {
    Write-Error "Failed to create script: $_"
    exit 1
}
