#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Fills the News Headlines section of a diary entry.

.DESCRIPTION
    Reads the news output file generated by the news skill's Get-AllNews.ps1,
    and injects it into the diary entry. Runs Get-AllNews.ps1 first if no
    output exists for the given date.

.PARAMETER Date
    The date for the diary entry in yyyy-MM-dd format. Defaults to today.

.PARAMETER EntryPath
    The full path to the diary entry file to update.

.EXAMPLE
    .\040-news.ps1 -Date 2026-02-28 -EntryPath ..\entries\2026-02-28.html
#>

[CmdletBinding()]
param(
    [string]$Date = (Get-Date -Format 'yyyy-MM-dd'),
    [string]$EntryPath
)

$ErrorActionPreference = 'Stop'
$InformationPreference = 'Continue'

. (Join-Path $PSScriptRoot 'HtmlDiaryHelpers.ps1')

function Test-NewsOutputQuality {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object]$News,

        [Parameter(Mandatory = $true)]
        [string]$Date
    )

    if (-not $News -or -not $News.Categories) { return $false }

    $headlineCount = 0
    foreach ($category in @($News.Categories)) {
        $articleCount = @($category.Articles).Count
        $headlineCount += $articleCount
        if ($articleCount -lt 3) { return $false }
    }

    if ($headlineCount -lt 16) { return $false }

    if ($News.GeneratedAt) {
        $generatedAt = [datetimeoffset]::Parse([string]$News.GeneratedAt)
        $targetDate = [datetime]::ParseExact($Date, 'yyyy-MM-dd', $null)
        $targetEnd = [datetimeoffset]::new($targetDate.AddDays(1))
        if ($generatedAt.Date -eq $targetDate.Date -and $generatedAt.Hour -lt 6 -and [datetimeoffset]::Now -ge $targetEnd) {
            return $false
        }
    }

    return $true
}

# --- Resolve entry path ---
if (-not $EntryPath) {
    $EntryPath = Get-DiaryHtmlEntryPath -ScriptRoot $PSScriptRoot -Date $Date
}

if (-not (Test-Path $EntryPath)) {
    Write-Error "Diary entry not found: $EntryPath"
    exit 1
}

# --- Locate news output ---
$newsOutputDir = Join-Path $env:USERPROFILE (Join-Path '.agents' (Join-Path 'skills' (Join-Path 'news' 'output')))
$newsFile = Join-Path $newsOutputDir "$Date.json"

$allNewsScript = Join-Path $env:USERPROFILE (Join-Path '.agents' (Join-Path 'skills' (Join-Path 'news' (Join-Path 'scripts' 'Get-AllNews.ps1'))))
$shouldGenerate = -not (Test-Path $newsFile)

if (-not $shouldGenerate) {
    $existingNews = Get-Content $newsFile -Raw | ConvertFrom-Json
    $shouldGenerate = -not (Test-NewsOutputQuality -News $existingNews -Date $Date)
    if ($shouldGenerate) {
        Write-Information "`e[1;33mNews output for $Date failed quality checks. Regenerating...`e[0m"
    }
}

if ($shouldGenerate -and (Test-Path $allNewsScript)) {
    Write-Information "`e[1;33mGenerating news output for $Date...`e[0m"
    & $allNewsScript -Date $Date -Count 7 -HoursBack 48 6>&1 | Out-Null
}

if (-not (Test-Path $newsFile)) {
    Write-Information "`e[1;31mNo news output available for $Date. Skipping.`e[0m"
    return
}

# --- Read the news output ---
$news = Get-Content $newsFile -Raw | ConvertFrom-Json

if (-not $news -or -not $news.Categories) {
    Write-Information "`e[1;31mNews output file is empty for $Date. Skipping.`e[0m"
    return
}

if (-not (Test-NewsOutputQuality -News $news -Date $Date)) {
    Write-Information "`e[1;31mNews output for $Date is still below quality threshold. Skipping injection.`e[0m"
    return
}

Write-Information "`e[1;36mInjecting news headlines into diary entry...`e[0m"

$htmlLines = @(
    '<div class="card diary-generated-markdown">',
    "  <div class=""eyebrow"">News snapshot for $Date</div>"
)
$headlineCount = 0

foreach ($category in @($news.Categories)) {
    $htmlLines += "<h3>$([System.Net.WebUtility]::HtmlEncode($category.Title))</h3>"
    $htmlLines += '<ol class="num-list">'

    foreach ($article in @($category.Articles)) {
        $title = [System.Net.WebUtility]::HtmlEncode($article.Title)
        $url = [System.Net.WebUtility]::HtmlEncode($article.Link)
        $source = [System.Net.WebUtility]::HtmlEncode($article.Source)
        $htmlLines += "<li><a href=""$url"">$title</a> <span class=""tag tag-slate"">$source</span></li>"
        $headlineCount++
    }

    $htmlLines += '</ol>'
}

$htmlLines += '</div>'
$sectionHtml = $htmlLines -join "`n"
Set-DiarySectionInnerHtml -EntryPath $EntryPath -SectionTitle '📰 News Headlines' -InnerHtml $sectionHtml
Write-Information "`e[1;32mNews headlines injected into diary entry.`e[0m"
Write-Information "  Categories: $($news.Categories.Count) | Headlines: $headlineCount"
