#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Fills the News Headlines section of a diary entry.

.DESCRIPTION
    Reads the news output file generated by the news skill's Get-AllNews.ps1,
    and injects it into the diary entry. Runs Get-AllNews.ps1 first if no
    output exists for the given date.

.PARAMETER Date
    The date for the diary entry in yyyy-MM-dd format. Defaults to today.

.PARAMETER EntryPath
    The full path to the diary entry file to update.

.EXAMPLE
    .\040-news.ps1 -Date 2026-02-28 -EntryPath ..\entries\2026-02-28.html
#>

[CmdletBinding()]
param(
    [string]$Date = (Get-Date -Format 'yyyy-MM-dd'),
    [string]$EntryPath
)

$ErrorActionPreference = 'Stop'
$InformationPreference = 'Continue'

. (Join-Path $PSScriptRoot 'HtmlDiaryHelpers.ps1')

# --- Resolve entry path ---
if (-not $EntryPath) {
    $EntryPath = Get-DiaryHtmlEntryPath -ScriptRoot $PSScriptRoot -Date $Date
}

if (-not (Test-Path $EntryPath)) {
    Write-Error "Diary entry not found: $EntryPath"
    exit 1
}

# --- Locate news output ---
$newsOutputDir = Join-Path $env:USERPROFILE '.agents' 'skills' 'news' 'output'
$newsFile = Join-Path $newsOutputDir "$Date.md"

if (-not (Test-Path $newsFile)) {
    # Try to generate it
    $allNewsScript = Join-Path $env:USERPROFILE '.agents' 'skills' 'news' 'scripts' 'Get-AllNews.ps1'
    if (Test-Path $allNewsScript) {
        Write-Information "`e[1;33mNews output not found for $Date. Generating...`e[0m"
        & $allNewsScript 6>&1 | Out-Null
    }

    if (-not (Test-Path $newsFile)) {
        Write-Information "`e[1;31mNo news output available for $Date. Skipping.`e[0m"
        return
    }
}

# --- Read the news output ---
$newsContent = (Get-Content $newsFile -Raw).Trim()

if (-not $newsContent) {
    Write-Information "`e[1;31mNews output file is empty for $Date. Skipping.`e[0m"
    return
}

Write-Information "`e[1;36mInjecting news headlines into diary entry...`e[0m"

# --- Count headlines for reporting ---
$headlineCount = ([regex]::Matches($newsContent, '^\|\s*\d+\s*\|', 'Multiline')).Count
$categoryCount = ([regex]::Matches($newsContent, '^###\s+', 'Multiline')).Count

$lines = $newsContent -split '\r?\n'
$htmlLines = @(
    '<div class="card diary-generated-markdown">',
    "  <div class=""eyebrow"">News snapshot for $Date</div>"
)
$currentCategoryOpen = $false

foreach ($line in $lines) {
    if ($line -match '^###\s+(.+)$') {
        if ($currentCategoryOpen) {
            $htmlLines += '</ol>'
        }
        $htmlLines += "<h3>$([System.Net.WebUtility]::HtmlEncode($Matches[1]))</h3>"
        $htmlLines += '<ol class="num-list">'
        $currentCategoryOpen = $true
        continue
    }

    if ($line -match '^\|\s*\d+\s*\|\s*\[(.+?)\]\((.+?)\)\s*\|\s*(.+?)\s*\|$') {
        $title = [System.Net.WebUtility]::HtmlEncode($Matches[1])
        $url = [System.Net.WebUtility]::HtmlEncode($Matches[2])
        $source = [System.Net.WebUtility]::HtmlEncode($Matches[3])
        $htmlLines += "<li><a href=""$url"">$title</a> <span class=""tag tag-slate"">$source</span></li>"
    }
}

if ($currentCategoryOpen) {
    $htmlLines += '</ol>'
}

$htmlLines += '</div>'
$sectionHtml = $htmlLines -join "`n"
Set-DiarySectionInnerHtml -EntryPath $EntryPath -SectionTitle '📰 News Headlines' -InnerHtml $sectionHtml
Write-Information "`e[1;32mNews headlines injected into diary entry.`e[0m"
Write-Information "  Categories: $categoryCount | Headlines: $headlineCount"
